config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


# TODO
# DATA BRICKS
# generate restaurant model
   # rails generate model restaurant name:string rating:integer
   # rails generate we specify that it is the model later the name of the model and then key value pares name: string, and we also want the rating of it which is a integer
   # this generates migration file and it has a timestrap itself and it creates the model file itself too
# seed some sample data

# APPLICATIVE BRICKS
# generate restaurants controller

# USER ACTIONS (in silo R->C->V)
# read all restaurants
# read one
# create new
# update one
# delete one


#now we have created restaurants controller so we add here:

get "restaurants/new", to: "restaurants#new", as:'new_restaurant'
# NEW BEFORE SHOW
#we need two requests:
# 1. GET the restaurant creation form = 1 request
# 2. POST the parameters to create a new restaurant = 1 request
post "restaurants", to: "restaurants#create"
# we have to save it adn we dont need as cause we will never link it to this
get '/restaurants', to: 'restaurants#index'
#index is read all option by convention

# find one by id should look like this
#GET http://localhost:3000/restaurants/4
# so after restaurants we have /4 which is id
get "restaurants/:id", to: "restaurants#show", as: 'restaurant'
# To update some restaurant:
get "restaurants/:id/edit", to: "restaurants#edit", as:'edit_restautant'
# Patch replaces restaurant with new info
patch "restaurants/:id", to: "restaurants#update"
# Delete a restaurant
delete "restaurants/:id", to: "restaurants#destroy", as: 'destroy_restaurant'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # restaurant model that is inheriting from application record which is abstract and it connects all of it to active record
  #just it means it will have active record available
  # look at migration file in db
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    #fetch all reastaurants and we put it in instance variable!
    @restaurants = Restaurant.all
  end
  #after this we create index.html.erb in view to display it

  def new
    @restaurant = Restaurant.new
    # Needed to instantiate the form_with
  end

  def create
    @restaurant = create!(params[:restaurant])
    # @restaurant.save (CREATE IS SAVE + NEW)
    redirect_to restaurant_path(@restaurant)
    # redirect is to send them to this page so they see that it is added basically we just send them to see all list of restaurants but even without this it saves it
    # Will raise ActiveModel::ForbiddenAttributesError in order to solve that we need to do this:
    # and private part:
    # private
    # def restaurant_params
    # params.require(:restaurant).permit(:name, :address, :rating)
    # end
    # No need for app/views/restaurants/create.html.erb cause it is something happening behind the scenes post patch and delete dont need a new view cause it is not presented to user so no view
  end

  def show
    # to find one restaurant by index
    @restaurant = Restaurant.find(params[:id].to_i)
    # ovde ga nadjemo i dodelimo instance varijabli @restaurant i onda u view koristimo da mu prezentujemo ime,addresu i rating
    # params is from ruby that console not console but from serve raise
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(params[:restaurant])
    redirect_to restaurant_path(@restaurant)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # No need for destroy.html.erb
    redirect_to restaurants_path, status: :see_other
    # this status means not to try to find this resto anymore cause it is deleted so just see others 
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
    # this gives us permit to use stuff and it is always same!
    # strong params manually and specifically permit paramenters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>
  
  <%= f.submit %>
<% end %>

<%# gives us this html %>
<%# <form action="/restaurants/1" accept-charset="UTF-8" method="post">
  <input type="hidden" name="_method" value="patch"><input type="hidden" name="authenticity_token" value="N47B9uuCscf1TMPr56jIyLE9RrA+65tv4TC6Ks+UO96ZLg9hTaqYE9NiAuozjZkjxGGa/AXIYREuZ6KSu427IQ==">
  <label for="restaurant_name">Name</label>
  <input type="text" value="the spoon" name="restaurant[name]" id="restaurant_name">
  <label for="restaurant_address">Address</label>
  <input type="text" value="Avenue Charles-Quint 365, 1083 Ganshoren, Belgique" name="restaurant[address]" id="restaurant_address">
  <label for="restaurant_rating">Rating</label>
  <input type="number" value="4" name="restaurant[rating]" id="restaurant_rating">
  <input type="submit" name="commit" value="Update Restaurant" data-disable-with="Update Restaurant">
</form> %>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |resto| %>
    <li><%= link_to resto.name, restaurant_path[resto.id]%></li>
  <% end %>
</ul>
<%= link_to 'Add restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_with model: @restaurant do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :address %>
  <%= form.text_field :address %>

  <%= form.label :rating %>
  <%= form.number_field :rating %>

  <%= form.submit %>
<% end %>
<%# new way to write forms %>
<%# it gives form in this html %>
<%# <form action="/restaurants" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="fUrBymmVzFG49YTQE9xKfohttEtW7eHnui2WT6KWpRXT6g9dz73lhZ7bRdHH+RuV/TFoB23OG5l1eo731o8l6g==">
  <label for="restaurant_name">Name</label>
  <input type="text" name="restaurant[name]" id="restaurant_name">
  <label for="restaurant_address">Address</label>
  <input type="text" name="restaurant[address]" id="restaurant_address">
  <label for="restaurant_rating">Rating</label>
  <input type="number" name="restaurant[rating]" id="restaurant_rating">
  <input type="submit" name="commit" value="Create Restaurant" data-disable-with="Create Restaurant">
</form> %>
<%# form for user to add inside new restaurant so we ask him for all data that is needed, name, address, rating %>
<%# HERE WE MADE A GET PAGE, now we also need POST PAGE TO SAVE IT IN ACTIVE RECORD %>
<%= link_to 'go back', restaurant_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= "*" * @restaurant.rating %></p>
<%# good practice is to call making the views in terminal with touch and specifying the path %>
<%# good so that people dont choose restaurant by index but by name we do that in index html %>
<%= link_to 'go back', restaurant_path %>
<%= link_to 'edit', edit_restaurant_path(@restaurant.id) %>
<%# these paths are  from as part %>
<%= link_to 'delete', destroy_restaurant_path(@restaurant.id)
data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>